spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.113/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.20.112
    port: 6479
server:
  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.imooc.LoggerTest: debug

wechat:
  mpAppId: wxd3748593n2n
  mpAppSecret: 2957snci48829sxdn22349jsw
  openAppId: wxnh38fan2bfh26shg75h3y4n
  openAppSecret: 91msm4mvh47fh57f5hfb3nnsg2ksug86
  mchId: 23456256542
  mchKey: 8573hsmxkw6395kaanxue243
  ketPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqqo28dwn2nHH*G&RFG88H66dE6h9w

projectUrl:
  wechatMpAuthorize: http://sell.natapp4.cc
  wechatOpenAuthorize: http://sell.natapp4.cc
  sell: http://sell.natapp4.cc

